### ISSUE TITLE
support named instances

### ISSUE THREAD

**Issue by polivbr** [kardeiz/bb8-tiberius#5]
The ConnectionManager currently only supports connecting with a host and a port. I have a need to connect via named instance, which is supported in Tiberius via the sql-browser features and the connect_named() extension to TcpStream.

I've submitted a pull request which adds this functionality.

**Comment by kardeiz** [comment]
Sorry about that, I never received an email notice for this or your PR. I've merged the PR and released a new version `0.7.0` of this library.

I modified your PR slightly to add a `use_named_connection` flag on the ConnectionManager builder, so that users could go with the default behavior even with the feature flag enabled.
